name: Deploy Quarto site to Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install jupyter numpy statsmodels

      - uses: quarto-dev/quarto-actions/setup@v2

      - name: Show versions & tree
        run: |
          python --version
          pip show jupyter nbformat numpy statsmodels || true
          quarto --version
          echo "---- _quarto.yml ----"
          cat _quarto.yml || true
          echo "---- tree ----"
          ls -la

      - name: Render site (debug)
        run: |
          set -euxo pipefail
          quarto check install
          # 디버그 로그 + 캐시 무시
          quarto render --log-level debug --no-cache 2>&1 | tee render-debug.log

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: _site

      # 실패 시 디버그 로그 업로드
      - name: Upload render log on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: render-debug-log
          path: render-debug.log

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
